version: '3.8'
services:
  mongodb:
    image: "mongo"
    container_name: mongodb
    ports:
      - "27027:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    image: "backend"
    container_name: backend_application
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: "mongodb://mongodb:27017"

volumes:
  mongodb_data:
